### ISSUE TITLE
Consider using PyQT5 where possible

### ISSUE THREAD

**Issue by auvipy** [yunit-io/yunit#12]
this should reduce development and maintenance burden. thoughts?

**Comment by markures** [comment]
Isn't it less optimized? It could require more resources, am I wrong?

**Comment by z3ntu** [comment]
Right now Unity 8 is exactly 0% Python code so rewriting everything wouldn't help anyone.

**Comment by WernerLDev** [comment]
Isn't the whole user interface currently written using QML? This is already a lot less low-level then pure C++ so I don't see a reason to switch to something else.

**Comment by jsalatas** [comment]
I agree with @WernerLDev. Let's stick to QML :)

**Comment by ShFil119** [comment]
"Right now Unity 8 is exactly 0% Python code so rewriting everything wouldn't help anyone."
Nope. Look inside Tests.
@auvipy,
usually python's code is less efficient than binary programs from c++ code, i mean raw performance. Unity is heavy, so we shouldn't belittle optimization.

**Comment by hasselmm** [comment]
Lesson learned from Canonical: Let's stick with standard way of doing things, instead of reinventing the wheel, when it comes to purely technical aspects. The well supported standard with strong maintenance promise is C++ and QML, so let's stick with that.

Still worth to consider to keep any plugin API friendly to other programming languages.

**Comment by z3ntu** [comment]
@ShFil119 Tests aren't a part of the main codebase of Unity 8, but as you said for the tests (and yes, I was aware of that).

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
