### ISSUE TITLE
Direction of development?

### ISSUE THREAD

**Issue by ShFil119** [yunit-io/yunit#9]
I think discussion at this stage is important. This will prevent useless work.

Mainly I think about finding a gap for unity and reasons why distros/companies should choose it.
 
My proposal are professional/business systems.
Like OpenSUSE, RHEL/CentOS. They have been using modified gnome 3, but after "liberation",  maybe they will be interested in Unity.

**Comment by jsalatas** [comment]
Agree with that. Can we please discuss it at the mailing list? :)

https://unity8.org/cgi-bin/mailman/listinfo/dev

**Comment by stavpup** [comment]
IMHO it is important to establish what is so special about Unity8 and what are the advantages it has over other projects like gnome shell, MATE, Cinammon, XFCE, LXQT etc.

**Comment by lben** [comment]
The HUD is a must to me and I think it can make anyone productive in no time. 

Sorry for not posting this on the mailing list since I am not a c++ developer and I never understood what is so good about mailing lists. Personally I prefer github issues

**Comment by KoczurekK** [comment]
@lben Don't worry, I'm a C++ dev and neither understand what's so good 'bout them. IMHO:
- GitHub Issues – interaction with community
- Slack – internal communication

Back to HUD, yes, this must be implemented, we all know that power of Unity is its productivity and ergonomy, HUD was great step forward. I'm actually amazed that it isn't already implemented in U8.

**Comment by CreamyCookie** [comment]
I agree with @lben. Most importantly, I think are:

- [] [The HUD](https://wiki.ubuntu.com/Unity/HUD) and a global menu

- [ ] ![Quicklists and progress bars on launcher icons](https://cloud.githubusercontent.com/assets/3063858/24778218/b3dc2e5a-1b29-11e7-9362-515339d9ebe4.png)

- [ ] ![Good shortcuts and an easy way to view them](https://cloud.githubusercontent.com/assets/3063858/24778322/3744781a-1b2a-11e7-9f12-7d3d80370181.png)

I think it would be pretty neat if Unity had a flexible plugin architecture for searches, so that it could be used for calculations, accessing older clipboard entries or setting timers. Or maybe parts of [Kupfer](https://github.com/kupferlauncher/kupfer) could be directly integrated to not reinvent the wheel.

**Comment by jsalatas** [comment]
IMHO, at this initial point, I guess our first decision should be about Mir vs wayland. It seems clear to me that most of us want to switch to wayland. But is this possible to happen? I guess we need to investigate it and focus at this for now.

**Comment by aissat** [comment]
One of the best projects to develop a single project is better than working on two projects, but it is a difficult to switch to Wayland  but the most difficult it's  develop tow projects Mir and unity8

**Comment by jsalatas** [comment]
As I suggested (actually thinking out loud) to the mailing list, maybe we should consider/evaluate KDE's KWin

https://community.kde.org/KWin/Wayland

which already works with wayland (desktop and mobiles). Maybe it's worth looking at it rather that starting from scratch :\

**Comment by aissat** [comment]
@jsalatas I support this view

**Comment by jadenPete** [comment]
I think Unity 8 should totally head in the direction of a easily portable, customizable desktop. Unity 7 was stuck at it's default setup, as it took a long time for even the ability to move the panel. Gnome 3 is similar. Unity 8 should be extensible and **easily portable to other distros** while remaining customizable on its own.

**Comment by jadenPete** [comment]
KWin is also a very smart choice. We should not waste time on supporting XOrg.

**Comment by KoczurekK** [comment]
KWin also seems like a neat idea to me. As it was said earlier - whole
kde5-frameworks will most likely be useful.

7 kwi 2017 04:38 "jadenPete" <notifications@github.com> napisał(a):

**Comment by the-Mitu** [comment]
Hello,
I have posted my idea on the vision Ubuntu Phone and a convergence as a whole on UbPorts forum (as Ubports' Martin declared on Google+ his commitment to keeping Ubuntu Phone's alive).

https://forums.ubports.com/topic/170/a-vision-of-where-to-go-after-ubuntu-touch-s-death

There is a major question in my opinion: do we want the Unity 8 to become yet another cool desktop environment or still pursue the vision which Canonical brought us to this point with - phones and convergence?

**Comment by Gspohu** [comment]
Yes it's a good question, because if we want to keep the convergence in unity8 we need to support some soft like Aethercast.

**Comment by the-Mitu** [comment]
As I stated in tle linked posts, if we want to keep the convergence, we should take the Ubuntu Core as a base. I don't say that the DE has to be Core only, but in case of convergence snaps would be the best way to go - we would still use much work done by Canonical and not duplicate it.

In the meantime, there is another fork being created: https://unity.ubports.com/

**Comment by ABHC** [comment]
I have read your post Mitu there are some good ideas. 

I'm agree with you, we must fight for convergence. The creed of Ubuntu is _"linux for humans"_  so if we want stay with this philosophy, unity8 should work on touch devices and all kinds of devices not only computers. 

So a debate of what philosophy we want for this project is necessary.

**Comment by jsalatas** [comment]
Hmmm..... most people are positive about convergence, so I guess this is the way to go :)

My only objection comes from the fact that canonical abandoned it, but what the ****, community can achieve more than a company. Right? :)

Also another point I want to raise, is that I wouldn't ant to see a crippled desktop version just for sake of convergence :\

**Comment by the-Mitu** [comment]
That is true.

But that began to change just before Unity 8 was discontinued. Workspaces were coming for example and other features as well.

That reminded me of one think: forking master is not enough, there were many branches that had much work done as well, but not yet merged!

I believe that all of us should unite around Ubports' initiative - they have the infrastructure and knowledge about the devices. And they are already organized - webpage, discussion groups, forum, etc. I don't think they could stop their actions and join here, so that is more the question if devs from here join with them on their vision or start something different on their own.

**Comment by jsalatas** [comment]
UBPorts have a meeting to discuss all these stuff and they will keep us updated. Let's see how it goes.

**Comment by the-Mitu** [comment]
When and where will this meeting be held? I might want to join it.

**Comment by jsalatas** [comment]
You can join their group in Telegram and ask. There should be a link somewhere in their website :)

**Comment by m8m5** [comment]
ubports telegram https://ubports.com/telegram

**Comment by the-Mitu** [comment]
Seems like I'll have to register on Telegram someday... I will look at it when I have some time.

**Comment by m8m5** [comment]
@the-Mitu FYI after joining telegram group, you will not be able to see previous discussion :( .

**Comment by dtmonterrey** [comment]
I heard that the UBports dev meeting will be today at 18:00UTC

**Comment by the-Mitu** [comment]
Oh no, I am not available at this time :( I will join the group before so that I could read it later.

**Comment by NunuM** [comment]
Hello,
At first stage :
    * Nominate scrum master(s), someone who understand the whole system and take the major design decisions.
   * Stipulate the interval for releases.
   * Design the epic stories about the system, for each major "module", for the next release.

At second stage:
   * For each module, dissect into user stories,  and crate the uses cases, in order, to the community, work on them.

**Comment by vadrian89** [comment]
Hi guys, 

> I think Unity 8 should totally head in the direction of a easily portable, customizable desktop. Unity 7 was stuck at it's default setup, as it took a long time for even the ability to move the panel. Gnome 3 is similar. Unity 8 should be extensible and easily portable to other distros while remaining customizable on its own.

I agree on this heavily, if something Unity8 should bring customisations option from the base installation, launcher, colors for both launcher and panel, the trash icon being able to remove it or move it up the launcher, etc.  

Another thing, while my knowledge of display servers / compositors / window managers isn't much, I think Enlightenment would be a good choice because as of 0.20 version has full support while Kwin has incomplete support for Wayland(according to wikipedia).  

Related to convergence: Qt framework allows this easily, tough as a developer you need to take care as sometimes for mobile it might need aditional tweaking, but still, while working on my first project seems that Qt is a framework of the future with all the possibilities brings. Saying this I think it should be one of the goals the future DE should achieve.

**Comment by Mikacpikac** [comment]
I think best way to go is simillar to what LXQT does. Made shell for Plasma. Then just fork other components and rename them or stay dependent on Plasma.

**Comment by jsalatas** [comment]
Please use our mailing list for discussion regarding development

https://yunit.io/cgi-bin/mailman/listinfo/dev
